### ISSUE TITLE
Kinetic でGazeboに表示できない

### ISSUE THREAD

**Issue by MoriKen254** [CIR-KIT-Unit03/cirkit_unit03_simulator#19]
kineticで動作検証中なのですが、下記コマンド入力後、Gazeboが起動しても、Gazebo内の画面が真っ暗で何も表示されません。

```
roslaunch cirkit_unit03_gazebo cirkit_unit03_clearpath_playpen.launch
```

`kinetic-devel｀を作成してワーニングやエラー等はとったのですが。

コンソールはこんな感じです、最後の行で止まったままになります。

```
$ roslaunch cirkit_unit03_gazebo cirkit_unit03_clearpath_playpen.launch 
... logging to /home/nishidalab/.ros/log/73ff5eb2-5f29-11e7-9eb7-7c5cf8b6fdc8/roslaunch-nishidalab-hp-probook-450g2-1674.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://nishidalab-hp-probook-450g2:35668/

SUMMARY
========

PARAMETERS
 * /gains/base_to_left_rear_wheel/d: 10.0
 * /gains/base_to_left_rear_wheel/i: 0.5
 * /gains/base_to_left_rear_wheel/i_clamp: 3.0
 * /gains/base_to_left_rear_wheel/p: 100000.0
 * /gains/base_to_right_rear_wheel/d: 10.0
 * /gains/base_to_right_rear_wheel/i: 0.5
 * /gains/base_to_right_rear_wheel/i_clamp: 3.0
 * /gains/base_to_right_rear_wheel/p: 100000.0
 * /robot_description: <?xml version="1....
 * /rosdistro: kinetic
 * /rosversion: 1.12.7
 * /steer_bot_hardware_gazebo/enable_ackermann_link: True
 * /steer_bot_hardware_gazebo/front_steer: front_steer_joint
 * /steer_bot_hardware_gazebo/rear_wheel: rear_wheel_joint
 * /steer_bot_hardware_gazebo/virtual_front_steers: ['base_to_right_f...
 * /steer_bot_hardware_gazebo/virtual_front_wheels: ['base_to_right_f...
 * /steer_bot_hardware_gazebo/virtual_rear_wheels: ['base_to_right_r...
 * /steer_bot_hardware_gazebo/wheel_separation_h: 0.79
 * /steer_bot_hardware_gazebo/wheel_separation_w: 0.5
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    urdf_spawner (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [1688]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 73ff5eb2-5f29-11e7-9eb7-7c5cf8b6fdc8
process[rosout-1]: started with pid [1701]
started core service [/rosout]
process[gazebo-2]: started with pid [1720]
process[gazebo_gui-3]: started with pid [1730]
process[robot_state_publisher-4]: started with pid [1734]
process[urdf_spawner-5]: started with pid [1736]
SpawnModel script started
[ INFO] [1499001731.435029501]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1499001731.435885404]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[INFO] [1499001731.502130, 0.000000]: Loading model XML from ros parameter
[INFO] [1499001731.506464, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[INFO] [1499001732.111269, 0.000000]: Calling service /gazebo/spawn_urdf_model
```

以前 @AriYu さんに研究室でKinetic上で検証してもらったと思うのですが、あの時何か修正しましたか？
何かTipsがあれば教えてもらえたら嬉しいです。

そして、まだKineticの環境が研究室に残っているのなら、Gazeboで正常起動できるか確認したいです。

**Comment by AriYu** [comment]
確か、xacroでKineticに対応してないマクロがあったせいで起動しなかった気がします。
修正分をコミット、プッシュしてなかったかもしれません。
曖昧としてて大変申し訳ありません。

2017/07/02 22:36 "Masaru Morita" <notifications@github.com>:

kineticで動作検証中なのですが、下記コマンド入力後、Gazeboが起動しても、Gazebo内の画面が真っ暗で何も表示されません。

roslaunch cirkit_unit03_gazebo cirkit_unit03_clearpath_playpen.launch

`kinetic-devel｀を作成してワーニングやエラー等はとったのですが。

コンソールはこんな感じです、最後の行で止まったままになります。

$ roslaunch cirkit_unit03_gazebo cirkit_unit03_clearpath_playpen.launch
... logging to /home/nishidalab/.ros/log/73ff5eb2-5f29-11e7-9eb7-7c5cf8b6fdc8/roslaunch-nishidalab-hp-probook-450g2-1674.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://nishidalab-hp-probook-450g2:35668/

SUMMARY
========

PARAMETERS
 * /gains/base_to_left_rear_wheel/d: 10.0
 * /gains/base_to_left_rear_wheel/i: 0.5
 * /gains/base_to_left_rear_wheel/i_clamp: 3.0
 * /gains/base_to_left_rear_wheel/p: 100000.0
 * /gains/base_to_right_rear_wheel/d: 10.0
 * /gains/base_to_right_rear_wheel/i: 0.5
 * /gains/base_to_right_rear_wheel/i_clamp: 3.0
 * /gains/base_to_right_rear_wheel/p: 100000.0
 * /robot_description: <?xml version="1....
 * /rosdistro: kinetic
 * /rosversion: 1.12.7
 * /steer_bot_hardware_gazebo/enable_ackermann_link: True
 * /steer_bot_hardware_gazebo/front_steer: front_steer_joint
 * /steer_bot_hardware_gazebo/rear_wheel: rear_wheel_joint
 * /steer_bot_hardware_gazebo/virtual_front_steers: ['base_to_right_f...
 * /steer_bot_hardware_gazebo/virtual_front_wheels: ['base_to_right_f...
 * /steer_bot_hardware_gazebo/virtual_rear_wheels: ['base_to_right_r...
 * /steer_bot_hardware_gazebo/wheel_separation_h: 0.79
 * /steer_bot_hardware_gazebo/wheel_separation_w: 0.5
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    urdf_spawner (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [1688]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 73ff5eb2-5f29-11e7-9eb7-7c5cf8b6fdc8
process[rosout-1]: started with pid [1701]
started core service [/rosout]
process[gazebo-2]: started with pid [1720]
process[gazebo_gui-3]: started with pid [1730]
process[robot_state_publisher-4]: started with pid [1734]
process[urdf_spawner-5]: started with pid [1736]
SpawnModel script started
[ INFO] [1499001731.435029501]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1499001731.435885404]: waitForService: Service
[/gazebo/set_physics_properties] has not been advertised, waiting...
[INFO] [1499001731.502130, 0.000000]: Loading model XML from ros parameter
[INFO] [1499001731.506464, 0.000000]: Waiting for service
/gazebo/spawn_urdf_model
[INFO] [1499001732.111269, 0.000000]: Calling service /gazebo/spawn_urdf_model

以前 @AriYu <https://github.com/ariyu> さんに研究室でKinetic上で検証してもらったと思うのです
が、あの時何か修正しましたか？
何かTipsがあれば教えてもらえたら嬉しいです。

そして、まだKineticの環境が研究室に残っているのなら、Gazeboで正常起動できるか確認したいです。

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/CIR-KIT-Unit03/cirkit_unit03_simulator/issues/19>, or mute
the thread

**Comment by MoriKen254** [comment]
@AriYu 

ありがとう．その辺も見つけて取り敢えず動かせました．色々変えた分はpushしときます．
このissueは閉じます．
